umojaProject/article/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler500
from . import views
app_name = "article"

urlpatterns = [
    # path('dashboard/',views.dashboard,name = "dashboard"),
    path('resources/',views.resources,name = "resources"),
    path('internships/',views.internships,name = "internships"),
    path('programs/',views.programs,name = "programs"),
    # path('recent_articles/',views.recent_articles,name = "recent_articles"),
    # path('addarticle/',views.addArticle,name = "addarticle"),
    path('fellowships/',views.fellowships,name = "fellowships"),
    path('gallerys/',views.gallerys,name = "gallerys"),
    path('post_opportunity/', views.post_opportunity, name = "post_opportunity"),
    path('addInternship/',views.addInternship,name = "addInternship"),
    path('article/<slug:slug>/',views.detail,name = "detail"),
    path('addFellowship/',views.addFellowship,name = "addFellowship"),
    path('addImage/',views.addImage,name = "addImage"),
    path('addProgram/',views.addProgram,name = "addProgram"),
    path('addResource/',views.addResource,name = "addResource"),
    path('addArticle/',views.addArticle,name = "addArticle"),
    path('addProfile/',views.addProfile,name = "addProfile"),



    # path('update/<slug:slug>',views.updateArticle,name = "update"),
    # path('delete/<slug:slug>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<slug:slug>',views.addComment,name = "comment"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

umojaProject/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),

]

umojaProject/article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from trix.fields import TrixField

# Create your models here.

class Profile(models.Model):
    first_name = models.CharField(max_length=32, null=True)
    last_name = models.CharField(max_length=32, null=True)
    info = models.TextField(max_length=400,null=True)
    classof = models.CharField(max_length=32, null=True)
    picture = models.ImageField(upload_to='profile_pics', null=True)

    @property
    def __str__(self):
        return self.first_name + self.last_name

class Article(models.Model):
    author =models.CharField(max_length = 500,verbose_name = "Writer")
    title = models.CharField(max_length = 500,verbose_name = "Title")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Creation Date")
    article_image = models.FileField(upload_to='img', blank = True,null = True,verbose_name="Add Photos to Article")
    published = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, max_length=100,blank=True)


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Article, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_date']

class PostImages(models.Model):
    note = models.ForeignKey(Article,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='postImages',null=True,blank=True)

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Article",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "Name")
    comment_content = models.CharField(max_length = 200,verbose_name = "Comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

class Program(models.Model):
    program_company = models.CharField(max_length=100, null=True)
    diversity_program = models.CharField(max_length=100, null=True)
    diversity_link = models.CharField(max_length=100, null=True)
    diversity_industry = models.CharField(max_length=100, null=True)
    diversity_population = models.CharField(max_length=100, null=True)
    date_posted = models.DateTimeField(auto_now_add=True,verbose_name="Posted Date")
    admin_approved = models.BooleanField(default=False)
    class Meta:
        ordering = ['-date_posted']

class Internship(models.Model):
    internship_company = models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=100, null=True)
    link = models.CharField(max_length=100, null=True)
    industry = models.CharField(max_length=100, null=True)
    location = models.CharField(max_length=100, null=True)
    date_posted = models.DateTimeField(auto_now_add=True,verbose_name="Date")
    admin_approved = models.BooleanField(default=False)
    class Meta:
        ordering = ['-date_posted']

class Fellowship(models.Model):
    name = models.CharField(max_length=100, null=True)
    link =  models.CharField(max_length=100, null=True)
    location = models.CharField(max_length=100, null=True)
    date_posted = models.DateTimeField(auto_now_add=True,verbose_name="Posted")
    admin_approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date_posted']

class Resource(models.Model):
    title = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=1000, null=True)
    date_posted = models.DateTimeField(auto_now_add=True,verbose_name="Posted")
    content = RichTextField()
    admin_approved = models.BooleanField(default=False)
    class Meta:
        ordering = ['-date_posted']

class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery', null=True, blank=True)
    eventName = models.CharField(max_length=1000, null=True,blank=True)
    eventDate = models.CharField(max_length=1000, null=True, blank=True)
    date_posted = models.DateTimeField(auto_now_add=True,verbose_name="Posted")
    admin_approved = models.BooleanField(default=True)

    class Meta:
        ordering = ['-date_posted']

class Post(models.Model):
    content = TrixField('Content')



class FeaturedStudent(models.Model):
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Creation Date")
    name = models.CharField(max_length=50, null=True)
    image = models.ImageField(upload_to='gallery', null=True, blank=True)
    major = models.CharField(max_length=1000, null=True)
    classof = models.CharField(max_length=1000, null=True)
    description = models.CharField(max_length=1000, null=True)
    funfact = models.CharField(max_length=1000, null=True)
    published = models.BooleanField(default=True)

umojaProject/templates/models.py
from django.db import models

# Create your models here.

umojaProject/article/forms.py
from django import forms
from .models import Article, Internship, Fellowship, Program, Gallery, PostImages, Profile
from trix.widgets import TrixEditor

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["first_name","last_name","info","classof", "picture"]

class NoteFullForm(ArticleForm): #extending form
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    class Meta(ArticleForm.Meta):
        fields = ArticleForm.Meta.fields + ['images',]

class InternshipForm(forms.ModelForm):
    class Meta:
        model = Internship
        fields = ["internship_company","name","link","industry", "location"]

class FellowshipForm(forms.ModelForm):
    class Meta:
        model = Fellowship
        fields = ["name","link","location"]

class ProgramForm(forms.ModelForm):
    class Meta:
        model = Program
        fields = ["program_company","diversity_program","diversity_link","diversity_industry","diversity_population"]

class ImageForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ["image","eventName", "eventDate"]

from trix.widgets import TrixEditor

class EditorForm(forms.Form):
    content = forms.CharField(widget=TrixEditor)

umojaProject/article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm, InternshipForm, ImageForm, FellowshipForm, ProgramForm, ProfileForm
from .models import Article,Comment,Resource, Internship, Fellowship, Program, Gallery, Profile, FeaturedStudent
from django.contrib import messages
from django.template.defaultfilters import slugify
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail

def articles(request):
    keyword = request.GET.get("keyword")
    recent_articles = Article.objects.filter(published=True).order_by('-created_date')[:5]
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles , "recent_articles":recent_articles})

def recent_articles(request):
    recent_articles = Article.objects.filter(published=True).order_by('-created_date')[:8]
    return render(request,"index.html",{"recent_articles":recent_articles})

def about(request):
    profiles = Profile.objects.all()
    return render(request, "about.html", {'profiles': profiles})

def index(request):
    featuredStudents = FeaturedStudent.objects.filter(published=True).order_by('-created_date')[:5]
    return render(request,"index.html", {"featuredStudents":featuredStudents})


def post_opportunity(request):
    if request.method == "POST":
        message_name  = request.POST['message-name']
        message_email = request.POST['message']
        message = request.POST['message']

        send_mail(
        message_name,
        message,
        message_email,
        ['jmwai@conncoll.edu', 'mwaijohn244@gmail.com'],

        )

        return render(request, 'post_opportunity.html', {'message_name':message_name})
    else:
        return render(request, "post_opportunity.html", {})
def resources(request):
    resources = Resource.objects.filter(admin_approved=True)
    context = {
        "resources":resources
    }
    return render(request,"resources.html",context)


def internships(request):
    internships = Internship.objects.filter(admin_approved=True)
    return render(request, 'internships.html', {'internships':internships})

def fellowships(request):
    fellowships = Fellowship.objects.filter(admin_approved=True)
    return render(request, 'fellowships.html', {'fellowships':fellowships})

def programs(request):
    programs = Program.objects.filter(admin_approved=True)
    return render(request, 'programs.html', {'programs':programs})

def gallerys(request):
    gallerys = Gallery.objects.filter(admin_approved=True)
    return render(request, 'gallerys.html', {'gallerys':gallerys})

# def about(request):
#     return render(request,"about.html")

def addInternship(request):
    form = InternshipForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        internships = form.save(commit=False)
        internships.save()

        messages.success(request,"Internship Created Successfully")
        return redirect("article:internships")
    return render(request,"addInternship.html",{"form":form})

def addResource(request):
    form = InternshipForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        internships = form.save(commit=False)
        internships.save()

        messages.success(request,"Resource Created Successfully")
        return redirect("article:internships")
    return render(request,"addInternship.html",{"form":form})

def addProgram(request):
    form = ProgramForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        programs = form.save(commit=False)
        programs.save()

        messages.success(request,"Program Created Successfully")
        return redirect("article:programs")
    return render(request,"addProgram.html",{"form":form})

def addFellowship(request):
    form = FellowshipForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        fellowships = form.save(commit=False)
        fellowships.save()

        messages.success(request,"Fellowship Created Successfully")
        return redirect("article:fellowships")
    return render(request,"addFellowship.html",{"form":form})

def addImage(request):
    form = ImageForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        gallerys = form.save(commit=False)
        gallerys.save()

        messages.success(request,"Image Added Successfully")
        return redirect("article:gallerys")
    return render(request,"addImage.html",{"form":form})

def addProfile(request):
    form = ProfileForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        about = form.save(commit=False)
        about.save()

        messages.success(request,"Profile Added Successfully")
        return redirect("about")
    return render(request,"addProfile.html",{"form":form})
# def addAchievement(request):
#     form = ArticleForm(request.POST or None,request.FILES or None)
#
#     if form.is_valid():
#         article = form.save(commit=False)
#         article.save()
#
#         messages.success(request,"Article Created Successfully")
#         return redirect("article:articles")
#     return render(request,"addAchievement.html",{"form":form})

def detail(request,slug):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article, slug=slug)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article, "comments":comments })

def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.slug = slugify(article.title)
        article.save()

        messages.success(request,"Article Created Successfully")
        return redirect("article:articles")
    return render(request,"addarticle.html",{"form":form})


def addComment(request,slug):
    article = get_object_or_404(Article, slug=slug)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"slug":slug}))

umojaProject/templates/addFellowship.html
{% extends "layout.html" %}

{% block content%}
{% load crispy_forms_tags %}
<br><br><br><br>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Add Fellowship</h3>

        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Add Fellowship</button>
        </form>
    </div>
  </div>


{% endblock %}

umojaProject/templates/addImage.html
{% extends "layout.html" %}

{% block content%}
{% load crispy_forms_tags %}
<br><br><br><br>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Add Image</h3>

        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Add Image</button>
        </form>
    </div>
  </div>


{% endblock %}

umojaProject/templates/addInternship.html
{% extends "layout.html" %}

{% block content%}
{% load crispy_forms_tags %}
<br><br><br><br>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Add Internship</h3>

        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Add Internship</button>
        </form>
    </div>
  </div>


{% endblock %}

umojaProject/templates/articles.html
{% extends "layout.html" %}
{% block content %}
<section class="inner_page_breadcrumb bgc-f0 pt30 pb30" aria-label="breadcrumb">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h4 class="breadcrumb_title float-left"></h4>
      </div>
    </div>
  </div>
</section>

<div style="text-align:center; padding-bottom:-30px;" class ="alert alert-danger">
  <button type="button" class="btn btn-success" ><a href="{% url 'article:addArticle' %}">Add Article</a></button>
  <p style="font-style: italic;">Kindly Contribute to the Fellowship Opportunities database. The Fellowship opportunity added by you will only appear on the website after admin approval(This was neccessary
    to prevent bots from posting.) Thank you so much in advance for contributing</p>
</div>
<!-- Main Blog Post Content -->
	<section class="blog_post_container bgc-fa">
		<div class="container">
			<div class="row">
        <div class="col-lg-8">
				<div class="main_blog_post_content">
					<div class="row">
                    {% for article in articles %}
            <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5 pr15-xl">
              <div class="blog_grid_post mb35">
                <div class="thumb">
                  {% if article.article_image %}
    							 <a href="{% url 'article:detail' article.slug %}"><img class="img-fluid" src="{{article.article_image.url}}"   alt="Not Found" onerror=this.src="/media/images/blog/1.jpg" ></a>

                   {% else %}
                   	 <a href="{% url 'article:detail' article.slug %}"><img class="img-fluid" src="/media/images/blog/1.jpg"  alt="13.jpg"></a>
                       {% endif %}
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7 pl15-xl">
              <div class="blog_grid_post style2 mb35">
                <div class="details">
                  <a href="{% url 'article:detail' article.slug %}"><h4 style="color:blue;">{{ article.title}}</h4></a>
                  	<!-- <h5>@UmojaCamels: Posted by: {% if article.name %} {{article.name}} {% else%} Anonymous Post{% endif%}</h5> -->
                  <ul class="post_meta">
                    <li><a href="#"><span class="flaticon-clock"></span></a></li>
                    <li><a href="#"><span>Author: {% if article.name %} {{article.name}} {% else%} Anonymous Post{% endif%}</span></a></li>
                    <li><a href="#"><span>{{ article.created_date}}</span></a></li>
                    <!-- <li><a href="#"><span class="flaticon-chat"></span></a></li> -->

                  </ul>
                  <!-- <p> {{ article.content|truncatewords_html:15|safe }}</p> -->
                  <a class="text-thm" href="{% url 'article:detail' article.slug %}">Read More <span class="flaticon-right-arrow pl10"></span></a>
                </div>
              </div>
            </div>
            {%  endfor %}
					</div>
				</div>
        </div>
			</div>
		</div>
	</section>

{% endblock %}

umojaProject/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Control Board</h3>
<hr>
<p>
    Welcome, <small>{{request.user.username}}</small>
</p>
<hr>
<a class = "btn btn-danger" href = "{% url 'article:addarticle' %}">Add Article</a>
<hr>
{% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Hood</th>
            <th scope="col">Writer</th>
            <th scope="col">Date</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.slug %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.slug %}" class = "btn btn-danger">Update</a></td>
            <td><a href="{% url 'article:delete' article.slug %}" class = "btn btn-danger">Delete</a> </td>

          </tr>
          {% endfor %}

        </tbody>
      </table>
{% else %}

<div class = "alert alert-danger">
    You do not have an article yet ...

</div>
{% endif %}



{% endblock body %}

umojaProject/templates/detail.html
{% extends "layout.html" %}
{% block content %}
<!-- Main Blog Post Content -->
<section class="inner_page_breadcrumb bgc-f0 pt30 pb30" aria-label="breadcrumb">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h4 class="breadcrumb_title float-left"></h4>
      </div>
    </div>
  </div>
</section>

	<section class="blog_post_container bgc-fa">
		<div class="container">
			<div class="row">
				<div class="col-lg-8">
					<div class="main_blog_post_content">
						<div class="mbp_thumb_post">
              {% if article.article_image %}
               <a href="{% url 'article:detail' article.slug %}"><img class="img-fluid" src="{{article.article_image.url}}"   alt="Not Found" onerror=this.src="/media/images/blog/1.jpg" ></a>

               {% else %}
                 <a href="{% url 'article:detail' article.slug %}"><img class="img-fluid" src="/media/images/blog/1.jpg"  alt="13.jpg"></a>
                   {% endif %}
							<div class="details">
                <a href="{% url 'article:detail' article.slug %}"><h4 style="color:blue;">{{ article.title}}</h4></a>
                  <!-- <h5>@UmojaCamels: Posted by: {% if article.name %} {{article.name}} {% else%} Anonymous Post{% endif%}</h5> -->
                <ul class="post_meta">
                  <li><a href="#"><span class="flaticon-clock"></span></a></li>
                  <li><a href="#"><span>Author: {% if article.name %} {{article.name}} {% else%} Anonymous Post{% endif%}</span></a></li>
                  <li><a href="#"><span>{{ article.created_date}}</span></a></li>
                  <!-- <li><a href="#"><span class="flaticon-chat"></span></a></li> -->

                </ul>
<p>{{article.content|safe}}</p>
							</div>
							<!-- <ul class="blog_post_share">
								<li><p>Share This Post</p></li>
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-google"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
							</ul> -->
						</div>
            <div class="mbp_pagination_comments">
							<h4 class="title">Comments {% if comments %}({{comments.count }}){% endif %}</h4>
      <hr>
      {% if comments %}
      {% for comment in comments  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">

            <ul>
                <li class="list-inline-item"><a class="text-thm">{{ comment.comment_author}}</a></li>
                <li class="list-inline-item"><a href="#"><span class="flaticon-event"></span> {{comment.comment_date}}</a></li>
              </ul>
                {{comment.comment_content}}
          </div>
        </div>
      {% endfor %}


      {% else %}
      <div class ="alert alert-danger">
        This Post has no comments, be the first to comment!
      </div>
      {% endif %}
      </div>
						<div class="mbp_comment_form">
							<h4>Leave Your Review</h4>
							<form class="comments_form" method = "post" action = "{% url 'article:comment' article.slug %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="formGroupExampleInput">Name</label>
                    <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                  </div>
                <div class="form-group">
                    <label for="formGroupExampleInput">Comment</label>
                  <textarea name = "comment_content" class="form-control" rows="3"></textarea>
                </div>
								<button type="submit" class="btn btn-thm">Submit Comment <span class="flaticon-right-arrow"></span></button>
							</form>
						</div>
					</div>
				</div>

      </div>
    </div>
  </section>

  {% endblock %}

umojaProject/templates/internships.html
{% extends "layout.html" %}


{% block content %}
<section class="inner_page_breadcrumb bgc-f0 pt30 pb30" aria-label="breadcrumb">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h4 class="breadcrumb_title float-left"></h4>
      </div>
    </div>
  </div>
</section>
<!-- Our Candidate List -->
<div style="text-align:center; padding-bottom:-30px;" class ="alert alert-danger">
  <button type="button" class="btn btn-success" ><a href="{% url 'article:addInternship' %}">Add Internships</a></button>
  <p style="font-style: italic;">Kindly Contribute to the Internship database. The internship opportunity added by you will only appear on the website after admin approval(This was neccessary
    to prevent bots from posting.) Thank you so much in advance for contributing</p>
</div>


<section class="our-faq bgc-fa mt50">
  <div class="container">
    <div class="row">

      <div class="col-lg-12 col-xl-12">
        {% for internship in internships %}
          <div class="col-lg-12 mt30">
            <div class="fj_post style2 jlv5">
              <div class="details">
                <h5 class="job_chedule text-thm">{{internship.internship_company}}</h5>
                <h4>{{internship.name}}</h4>
                <p>{{internship.date_posted}} By: <a class="text-thm" href="#">Umoja Conncoll</a></p>
                <ul class="featurej_post">
                  <li class="list-inline-item"><span class="flaticon-location-pin"></span> <a href="#">{{internship.location}}</a></li>
                </ul>
              </div>
              <ul class="pjlv5">
                <li class="list-inline-item"> {{internship.industry}}</li>
                <li class="list-inline-item">
                  <a class="favorit" href="#"><span class="flaticon-favorites"></span></a>
                </li>
                <li class="list-inline-item">
                  <a class="btn btn-transparent" href="{{internship.link}}" target="_blank">Browse Internship</a>
                </li>
              </ul>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
</section>
{% endblock %}

umojaProject/templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Login</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}

            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Login</button>
        </form>
    </div>
  </div>

{% endblock body %}

umojaProject/templates/programs.html
{% extends "layout.html" %}
{% block content %}
<section class="inner_page_breadcrumb bgc-f0 pt30 pb30" aria-label="breadcrumb">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h4 class="breadcrumb_title float-left"></h4>
      </div>
    </div>
  </div>
</section>
<div style="text-align:center; padding-bottom:-30px;" class ="alert alert-danger">
  <button type="button" class="btn btn-success" ><a href="{% url 'article:addProgram' %}">Add Program</a></button>
  <p style="font-style: italic;">Kindly Contribute to the Diversity Programs database. The Program opportunity added by you will only appear on the website after admin approval(This was neccessary
    to prevent bots from posting.) Thank you so much in advance for contributing</p>
</div>
<section class="our-faq bgc-fa mt50">
  <div class="container">
    <div class="row">

      <div class="col-lg-12 col-xl-12">
        {% for program in programs %}
          <div class="col-lg-12 mt30">
            <div class="fj_post style2 jlv5">
              <div class="details">
                <h5 class="job_chedule text-thm">{{program.program_company}}</h5>
                <h4>{{program.diversity_program}}</h4>
                <h4>Target Group: {{program.diversity_population}}</h4>
                <p>{{program.date_posted}} By: <a class="text-thm" href="#">Umoja Conncoll</a></p>
                <ul class="featurej_post">
                  <li class="list-inline-item"><span class="flaticon-location-pin"></span> <a href="#">{{program.location}}</a></li>
                </ul>
              </div>
              <ul class="pjlv5">
                <li class="list-inline-item"> {{program.diversity_industry}}</li>
                <li class="list-inline-item">
                  <a class="favorit" href="#"><span class="flaticon-favorites"></span></a>
                </li>
                <li class="list-inline-item">
                  <a class="btn btn-transparent" href="{{program.link}}" target="_blank">Browse Program</a>
                </li>
              </ul>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
</section>
{% endblock %}

umojaProject/templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}

            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Register</button>
        </form>
    </div>
  </div>

{% endblock body %}

umojaProject/templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update Article</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Update Article</button>
        </form>
    </div>
  </div>


{% endblock body %}